config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :markus
  get 'markus/carousel', as: 'c'

  root 'markus#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/marku.rb
class Marku < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  def check
    redirect_to new_user_session_path unless user_signed_in?
  end

  protected

  def layout_by_resource
    if devise_controller?
      "auth"
    else
      "application"
    end
  end

end

app/controllers/markus_controller.rb
class MarkusController < ApplicationController
  before_action :check
  before_action :set_marku, only: [:show, :edit, :update, :destroy]

  # GET /markus
  # GET /markus.json
  def index
    @markus = Marku.all
  end

  # GET /markus/1
  # GET /markus/1.json
  def show
  end

  # GET /markus/new
  def new
    @marku = Marku.new
  end

  # GET /markus/1/edit
  def edit
  end

  # POST /markus
  # POST /markus.json
  def create
    @marku = Marku.new(marku_params)

    respond_to do |format|
      if @marku.save
        format.html { redirect_to @marku, notice: 'Marku was successfully created.' }
        format.json { render :show, status: :created, location: @marku }
      else
        format.html { render :new }
        format.json { render json: @marku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markus/1
  # PATCH/PUT /markus/1.json
  def update
    respond_to do |format|
      if @marku.update(marku_params)
        format.html { redirect_to @marku, notice: 'Marku was successfully updated.' }
        format.json { render :show, status: :ok, location: @marku }
      else
        format.html { render :edit }
        format.json { render json: @marku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markus/1
  # DELETE /markus/1.json
  def destroy
    @marku.destroy
    respond_to do |format|
      format.html { redirect_to markus_url, notice: 'Marku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marku
      @marku = Marku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marku_params
      params.require(:marku).permit(:post, :weight, :height, :month, :photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markus_helper.rb
module MarkusHelper
end

app/views/layouts/_errors.html.erb
<% if @marku.errors.any? %>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="alert alert-dismissable alert-danger" id="error_explanation">
        <h4>Ошибка!</h4>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <ul>
        <% @marku.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-default">
  <h6 class="text-right">
    <%= link_to 'Дмитрий Ройтман', 'http://geans.ru', class: "text-default text-right"%>
  </h6>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <%= link_to "Блог Маркуса", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% (1..12).to_a.each do |i| %>
          <li><a href="/markus/<%= i %>"><%= i %></a></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%#= link_to "Выход", destroy_user_session_path  %></li>
        <% else %>
          <li><%= link_to "Вход",  new_user_session_path %></li>
          <li><%= link_to "Регистрация",  new_user_registration_path %></li>
        <% end%>
      </ul>
    </nav>
  </header>

app/views/layouts/_jumbo.html.erb
    <div class="jumbotron">
      <h2>Welcome to the Ruby on Rails Tutorial</h2>
      <p>This is a home page for, <a href="http://salty-lake-1784.herokuapp.com/">Ruby on Rails Tutorial</a>  sample application.</p>
      <p><%= link_to "Sign up now!", signup_path, class: "btn btn-primary btn-lg"%></p>
    </div>
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-3">
        <div class="thumbnail">
          <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> 
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markus</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'ckeditor/ckeditor.js' %>
  <%#= javascript_include_tag 'ru.js' %>
  <%#= javascript_include_tag 'styles.js' %>
  <%#= javascript_include_tag 'config.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://markus.geans.ru/css/bootstrap-wysihtml5.css"></link>
  <link rel="stylesheet" type="text/css" href="http://markus.geans.ru/css/prettify.css"></link>
  <link rel="stylesheet" type="text/css" href="http://markus.geans.ru/css/bootstrap.min.css"></link>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
    <%#= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markus</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
</body>
</html>

app/views/markus/_form.html.erb
<div class="row">
  <div class="page-header">
     <h1 class="text-center">Блог Марчонка</h1>
  </div>
  <%= render 'layouts/errors'%>

  <div class="col-lg-offset-2 col-md-offset-md-2 col-sm-offset-sm-2 col-lg-8 col-md-8 col-sm-8" style="background-color: #eee; padding: 10 px;" >
    <%= form_for @marku, html: {class: "form-horizontal"} do |f| %>

    <fieldset >
        <legend>Опиши своего Марчонка</legend>

        <div class="form-group">
          <%= f.label :post, 'Сообщение:', class: "col-lg-3 control-label text-left" %>
          <div class="col-lg-9">
            <%= f.text_area :post, class: "form-control", placeholder: "Здесь какой-то текст:)", id: "txtarea" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :weight, 'Вес:', class: "col-lg-3 control-label text-left" %>
          <div class="col-lg-9">
            <%= f.text_field :weight, class: "form-control", placeholder: "Вес в килограммах" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :height, 'Рост: ', class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= f.password_field :height, class: "form-control", placeholder: "Рост в сантиметрах" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :month, 'Возраст:', class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= f.password_field :month, class: "form-control", placeholder: "Возраст в месяцах" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :photo, 'Ссылка на фото:', class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= f.password_field :photo, class: "form-control", placeholder: "Адрес фото" %>
          </div>
        </div>

        <div class="form-group">
          <hr />
          <div class="col-lg-offset-3 col-lg-9">
          <%= f.submit "OK", class: "btn btn-success" %>
          </div>
       </div>

    </fieldset>

    <% end %>
  </div>
</div>

<script src="http://markus.geans.ru/javascripts/wysihtml5-0.3.0.js"></script>
<script src="http://markus.geans.ru/javascripts/jquery-1.7.2.min.js"></script>
<script src="http://markus.geans.ru/javascripts/prettify.js"></script>
<script src="http://markus.geans.ru/javascripts/bootstrap.min.js"></script>
<script src="http://markus.geans.ru/javascripts/bootstrap-wysihtml5.js"></script>

<script>
    $('textarea').wysihtml5();
</script>

app/views/markus/edit.html.erb
<div class="container otstup">
  <%= render 'form' %>
  <ul class="pager">
      <li class="previous"><%= link_to 'Просмотреть', @marku  %> </li>
      <li class="next"><%= link_to 'Вернуться(Без сохранения) →', markus_path %></li>
  </ul>
</div>

app/views/markus/index.html.erb
    <div id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <% (1..11).to_a.each do |m| %>
            <li data-target="#myCarousel" data-slide-to="<%= m %>"></li>
          <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% @markus.each do |m| %>
            <div class="item <%= 'active' if m.id == 1 %>">
              <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=<%= "#{m.id}"%> month');"></div>
                <div class="carousel-caption">
                  <h1><%= link_to "#{m.id} Месяц", marku_path(m) %></h1>
                </div>
              </div>
            <% end %>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>

    <!-- JavaScript -->
    <script src="js/bootstrap.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

app/views/markus/new.html.erb
<div class="container otstup">
  <%= render 'form' %>
  <ul class="pager">
    <li class="previous">
    <%= link_to '← Назад(Не сохранять)', markus_path %>
    </li>
</div>

app/views/markus/show.html.erb
<div class="container otstup">
  <p id="notice"><%= notice %></p>
  

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Месяц:</strong> <%= @marku.month %></h3>
  </div>
  <div class="panel-body">
    <%= @marku.post %>
  </div>
  <div class="panel-footer">
    <h5><strong>Вес:</strong> <%= @marku.weight %> кг , <strong>Рост:</strong> <%= @marku.height %> см</h5>
  </div>
</div>
  <div class="thumbnail">
    <%= image_tag @marku.photo %>
  </div>
  <ul class="pager">    
    <li class="previous"><%= link_to 'Редактировать', edit_marku_path(@marku) %></li>
    <li class="next"><%= link_to 'Назад', markus_path %></li>
  </ul>